-- Generated by tools/generate_collision_footprints.lua. Do not edit by hand.
-- Source dimensions are derived from promoted opaque animation bounds.
return {
  ["luacrote_hero_headband_scooter"] = {
    source_animation = "omnidirectional_sprites",
    anchor = { x = 128, y = 224 },
    height_ratio = 0.1,
    width_ratio = 1,
    opaque_bounds = { left = 5, top = 1, right = 249, bottom = 255 },
    mask_width = 245,
    mask_height = 255,
    width = 245,
    height = 25.5,
    offset_x = -1,
    offset_y = 18.25
  },
  ["luacrotte_hero_motorcycle_direction_set_v001"] = {
    source_animation = "motorcycle_direction_set",
    anchor = { x = 32, y = 56 },
    height_ratio = 0.1,
    width_ratio = 1,
    opaque_bounds = { left = 1, top = 7, right = 62, bottom = 57 },
    mask_width = 62,
    mask_height = 51,
    width = 62,
    height = 5.1,
    offset_x = -0.5,
    offset_y = -1.55
  },
  ["motocrotte_bike_variant_01"] = {
    source_animation = "traffic_cycle",
    anchor = { x = 30, y = 58 },
    height_ratio = 0.1,
    width_ratio = 1,
    opaque_bounds = { left = 11, top = 11, right = 49, bottom = 58 },
    mask_width = 39,
    mask_height = 48,
    width = 39,
    height = 4.8,
    offset_x = 0,
    offset_y = -2.4
  }
}
