-- Input bindings are data so controls can be changed without editing systems.
return {
  move_left = { left = true },
  move_right = { right = true },
  move_up = { up = true },
  move_down = { down = true },
  jump = { space = true },
  drift = { lshift = true },
  cycle_drift_mode = { tab = true },
  cycle_control_schema = { tab = true },
  toggle_sprite_policy = { r = true },
  toggle_yaw = { y = true },
  cycle_movement_mode = { m = true },
  cycle_camera_mode = { c = true },
  cycle_background = { b = true },
  throttle = { t = true },
  brake = { x = true },
  gas_primary = { up = true },
  brake_primary = { down = true },
  drift_primary = { lshift = true },
  gas_fd = { f = true },
  brake_fd = { d = true },
  drift_fd = { s = true },
  dash = { d = true },
  profile_slot_1 = { ["1"] = true },
  profile_slot_2 = { ["2"] = true },
  profile_slot_3 = { ["3"] = true },
  profile_slot_4 = { ["4"] = true },
  profile_slot_5 = { ["5"] = true },
  profile_slot_6 = { ["6"] = true },
  profile_slot_7 = { ["7"] = true },
  profile_slot_8 = { ["8"] = true },
  profile_slot_9 = { ["9"] = true },
  toggle_visual_lab = { v = true },
  visual_yaw_left = { q = true },
  visual_yaw_right = { e = true },
  visual_radius_decrease = { k = true },
  visual_radius_increase = { m = true },
  trigger_effect = { e = true },
  ui_up = { up = true, w = true },
  ui_down = { down = true, s = true },
  ui_left = { left = true, a = true },
  ui_right = { right = true, d = true },
  ui_confirm = { ["return"] = true, space = true },
  ui_back = { escape = true },
  debug_toggle = { f3 = true },
  debug_masks = { f4 = true },
  debug_sensors = { f5 = true },
  debug_collisions = { f6 = true },
  debug_entities = { f7 = true },
  debug_camera = { f8 = true },
  debug_state = { f9 = true },
  debug_input = { f10 = true }
}
